[project]
name = "moonshots"
version = "0.1.0"
description = "make a milli"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[tool.setuptools]
packages = ["moonshots"]